### ISSUE TITLE
No responses from Bot

### ISSUE THREAD

**Issue by mcasaz** [OfficeDev/microsoft-teams-apps-expertfinder#13]
Followed the installation, no errors during deployment or when adding the app, just don't get anything back. Also don't have any errors, exception, failed requests in App Insights
![image](https://user-images.githubusercontent.com/33139177/87040956-c5eacd00-c1f1-11ea-8fc7-a0eeafc6e343.png)

**Comment by abbodh** [comment]
Hi @mcasaz - can you confirm if the deployment succeeded. There is a recent update happened in Azure app service environment causing build failure. We have an active PR #14 to fix the build failure.

**Comment by mcasaz** [comment]
@abbodh sorry I noticed only now that the deployment failed. Does that D:\ path refer to something I need on my computer? (I don't have a D drive)
![image](https://user-images.githubusercontent.com/33139177/87118248-2c67fd80-c27b-11ea-96cc-224b681c6387.png)

**Comment by abbodh** [comment]
yes, I am working on the fix as I shared in PR #14
