### ISSUE TITLE
100 Char limit in Skills, Interests fields

### ISSUE THREAD

**Issue by mcasaz** [OfficeDev/microsoft-teams-apps-expertfinder#17]
When adding skills or interested in the Bot chat, the fields are limited to 100 character.
Is it possible to increase this?
Interestingly when updating the Skills in Delve beyond 100 chars, all fields are displayed in the Bot

![image](https://user-images.githubusercontent.com/33139177/87543245-af86ba80-c6a4-11ea-93da-559ea194dc3e.png)

![image](https://user-images.githubusercontent.com/33139177/87543651-63884580-c6a5-11ea-9a7e-7f84112a1190.png)

**Comment by abbodh** [comment]
@mcasaz , you can increase the size by changing the maxLength for each fields in adaptive card. Check out this file - https://github.com/OfficeDev/microsoft-teams-apps-expertfinder/blob/master/Source/Microsoft.Teams.Apps.ExpertFinder/Cards/MyProfileCard.cs#L159
