### ISSUE TITLE
Which Sharepoint URL

### ISSUE THREAD

**Issue by Bds1972** [OfficeDev/microsoft-teams-apps-expertfinder#20]
Can you provide a little more guidance on what sharepoint URL? Is this the default for out tenant? eg https://abcco.sharepoint.com

**Comment by v-smahaj** [comment]
Thank you for asking. We just updated the documentation to include this information, please refer [Deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-expertfinder/wiki/Deployment-Guide) .
